### ISSUE TITLE
Project can't be MIT Licensed

### ISSUE THREAD

**Issue by OjasA** [Studios-of-Inkblot/Crunch#1]
GNU Bison is GPLed.

**Comment by WokSearedBacon** [comment]
GPL is compatible with MIT, according to GNU: http://www.gnu.org/licenses/license-list.en.html#X11License

**Comment by OjasA** [comment]
Reopened per discussion we had.

**Comment by WokSearedBacon** [comment]
Changed LICENSE to GPL v3, as we agreed.
